version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
     - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
